# File managed by pluginsync
sudo: false
language: go
go:
- 1.6.3
- 1.7.1
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.3
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: mGennnoouk5bexMkUFAoYwDNsB90v4lPX2hqvx4Opl6OXs4HB6mhW/zuwC+0voCGQo/tiMAxfSNMmQa7TlvK8HUirT2R3l8WLiqOd7ikJrbfUUOrRixhJEkNQ2sEtnovB3CHVCHbw/scKGIRQOkJvns9xEm1Nkkm9ZWb8/U8AAUkEJnxKIGywUQFuEqvuK16VV9xG+RVdiiHJsDWpRqJgs8nTFC54OtC58eTm5bWQXI95bnC14BiEBxdMuGzPY5T7UMP37EkyRGv4Y1H0crTHRG3sBInJ1nv4wh+6JL8JOYsALJcCQm1/yl5M9wjIa9W0v8Noi9nbtwdSnLVmLGMhDx23d1pLAlb2cw/zhlKjv5OHnOI+5MpVTGK+mMfnJ9Gxs5HsIV/NZriZpMp1thwyADbw/1WW6FSrQhZxL1CKfPWequpDWfK2ruuMYQ72o7F4l7clN7bgH3ZTWeuLBTxpmADht9NZ++bWdPYQbJoo61o8hYKKBNAaqG+2mjFcy6zNMPexsnUZquZLJxeCdxvCz7bFnW1TSuuoFqp23ubu8Sf/W+G/l08KFcEvJtAhkMSBipP4Mghq67VFkBTUMjqu+pEMIBUAFsKVMO14vD2TxUfR0axOhYpHGywfXn5L9PuDHi1VqCpwMFkhyoMEDcqC3X28ZudCiNsyguShrWadZo=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-load
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: mGennnoouk5bexMkUFAoYwDNsB90v4lPX2hqvx4Opl6OXs4HB6mhW/zuwC+0voCGQo/tiMAxfSNMmQa7TlvK8HUirT2R3l8WLiqOd7ikJrbfUUOrRixhJEkNQ2sEtnovB3CHVCHbw/scKGIRQOkJvns9xEm1Nkkm9ZWb8/U8AAUkEJnxKIGywUQFuEqvuK16VV9xG+RVdiiHJsDWpRqJgs8nTFC54OtC58eTm5bWQXI95bnC14BiEBxdMuGzPY5T7UMP37EkyRGv4Y1H0crTHRG3sBInJ1nv4wh+6JL8JOYsALJcCQm1/yl5M9wjIa9W0v8Noi9nbtwdSnLVmLGMhDx23d1pLAlb2cw/zhlKjv5OHnOI+5MpVTGK+mMfnJ9Gxs5HsIV/NZriZpMp1thwyADbw/1WW6FSrQhZxL1CKfPWequpDWfK2ruuMYQ72o7F4l7clN7bgH3ZTWeuLBTxpmADht9NZ++bWdPYQbJoo61o8hYKKBNAaqG+2mjFcy6zNMPexsnUZquZLJxeCdxvCz7bFnW1TSuuoFqp23ubu8Sf/W+G/l08KFcEvJtAhkMSBipP4Mghq67VFkBTUMjqu+pEMIBUAFsKVMO14vD2TxUfR0axOhYpHGywfXn5L9PuDHi1VqCpwMFkhyoMEDcqC3X28ZudCiNsyguShrWadZo=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-load
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: releases
  api_key:
    secure: VhwD6d7LbGBur3q3OVfLbUOywn2deS7kRUFIYwLzQ5RL9GTV1F1Ov9XS885UgmE0JmxZ2TSLq7aXXYzx92ct2frs4Y7RNfMfx+UBdMNL6VbgwgPA3bQNNLOSYH4QduxuVozLkAt0GQq+sjZr43q4yLALYWWt1nNQP1KWnJDWyJb+2gXuLYrIUFy/QJVvupgeripQy2l6cXGxxBN2eAxhpg0RQhWLvuC3va4DQS45wkhreyeyNZ/zYZz6z2MmT2FiXt3P+R9w9PYZFeoSG+i0QphXsMj7NQ683U16nXvi3uan9BsuaQB8ddj91ejLeIJOJJZmOSuZu398CTCriNLQcaobyirOcILxhB1WTDwHNIBMCoJvti1WHyDvP/WifeE5Yqo1uN1GrPBzQJZ3tRktOAE1QHhAuuh3FD/7Qc+fZOabJIffdBQwfoKr4VpRcsDTT/qPFRaD6aQNFvZPcqE/W5tnIvx1/Y4m2qWk4yIgUPRJaeFCUwxO5/Vzku6u3VLblYc+O0ERvN9AFGkYGJoYQWtgnEFr4VdCK0f7Koh+aaw3+3W3mGLjTc4Ax6Z7RmpSzV1sFZY2TElIzubXYgPnFZMHUnyNpIaa4apg5QCFD+5orLoFORRjIx5+DzKyb6PQq6kO8iw+OvoClM83ASrlK/YY8fS5elWt7mt51k+xC/E=
  file:
    - release/snap-plugin-collector-load_linux_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-collector-load
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
